version: '2'
#代码目录请在.env 文件中配置
services:
  b2c:
    image: 'wykrisdev/shopex-docker:php56-zendGuardLoader'
    ports:
      - 8002:80
    volumes:
      - ${coderoot}:/data/httpd
    links:
      - mysql
      # - ftp
      # - redis
    environment:
      #默认web的路径
      - WEBROOT="${webroot}"
      #默认zl文件的路径
      - LICENSE_PATH="${license_path}"
    networks:
      - ecstore

  # redis:
  #   image: redis
  #   hostname: redis
  #   ports:
  #     - "8379:6379"
  #   volumes:
  #     - ./storage/redis:/data
  #   networks:
  #     - ecstore

  mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: ecstore-mysql
    ports:
      - "8806:3306"
    volumes:
      - ${storage_path}/php56/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ecstore

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8005:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - ecstore

#   ftp:
#     image: bogem/ftp
#     hostname: ftp
#     environment:
#       - FTP_USER=ftp
#       - FTP_PASS=ftp
#       - PASV_ADDRESS=0.0.0.0
#     volumes:
#       - ./storage/ftp:/home/vsftpd
#     ports:
#       - "20:20"
#       - "21:21"
#       - "47400-47470:47400-47470"
#     networks:
#        - ecstore

networks:
  ecstore:
    driver: bridge
